spring.application.name=contact-hub-svp
spring.datasource.url=jdbc:mysql://localhost:3306/contact_hub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Preeti872@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true